TASK-121 Update Profile
yosuahutagalung/dkn-budidayaplus-backend pull request #41
Opened 2024-11-02 09:14 UTC by K24-github

This is for updating the profile, the features implemented are:
- Change First Name and Last Name
- Change Profile Picture

Let me know if you have any feedback!

2024-11-02 09:41 UTC, fiardiel requested changes
Good job, Kevin. The code works. However, there are some issues with it

Improvements that can be made include making a `UserProfileInput` schema class which takes `first_name`, `last_name`, and `image_name`.

2024-11-02 11:12 UTC, fiardiel commented
> > Good job, Kevin. The code works. However, there are some issues with it
> > Improvements that can be made include making a schema class which takes , , and .`` UserProfileInput``first_name``last_name``image_name ``
> 
> Theres already UpdateProfileSchema ? Do you want me to change the name?

``` py
# api.py

@router.put("/{username}/", response=UpdateProfileSchema)
def update_profile(request, username: str, payload_profile: UpdateProfileSchema):
    user = User(
        first_name = payload_profile.first_name,
        last_name = payload_profile.last_name,
        username = "08888888888"
    )
    user_profile = UserProfile(
        image_name = payload_profile.image_name
    )
    try:
        service = UpdateServiceImpl.update_profile(username, user_profile, user)
        result = UpdateProfileSchema(
            first_name=service["user"].first_name,
            last_name=service["user"].last_name,
            image_name=service["profile"].image_name
        )
        return result
    except UserProfile.DoesNotExist:
        raise HttpError(404, "Profile tidak ditemukan")
    except Exception as e:
        raise HttpError(500, str(e))
```

Oh sorry, I meant you don't need to create a `user` and `user_profile` instance, you can just input using your `UpdateProfileSchema` to your service. Inside of the service, you can just retrieve the user by using the username you have in the input schema object. This will simplify your code on the API does not require extra `User` and `UserProfile` object creation

2024-11-03 14:33 UTC, fiardiel approved these changes

2024-11-07 12:04 UTC, rauloaul approved these changes
Well, Rafi ardiel already mentioned it and it is quite good now. Good Job Kevin~

2024-11-07 17:23 UTC, merged